---
# Source: reloader/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: RELEASE-NAME-reloader-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: default

