---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    group: com.stakater.platform
    provider: stakater
    version: v0.0.39
    
  name: RELEASE-NAME-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: RELEASE-NAME-reloader
      release: "RELEASE-NAME"
  template:
    metadata:
      labels:
        app: RELEASE-NAME-reloader
        chart: "reloader-v0.0.39"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        group: com.stakater.platform
        provider: stakater
        version: v0.0.39
        
    spec:
      containers:
      - env:
        image: "stakater/reloader:v0.0.39"
        imagePullPolicy: IfNotPresent
        name: RELEASE-NAME-reloader
        args:
      serviceAccountName: reloader

