---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: reloader
    chart: "reloader-v0.0.38"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader

