---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader

