---
# Source: reloader/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: reloader
    group: com.stakater.platform
    provider: stakater
    version: 0.0.4
    chart: "reloader-0.0.4"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: reloader
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "stakater/reloader:0.0.4"
        imagePullPolicy: IfNotPresent
        name: reloader
      serviceAccountName: reloader
              
---
# Source: reloader/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: reloader
    group: com.stakater.platform
    provider: stakater
    version: 0.0.4
    chart: "reloader-0.0.4"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels: 
    app: reloader
    group: com.stakater.platform
    provider: stakater
    version: 0.0.4
    chart: "reloader-0.0.4"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader-role
  namespace: tools
rules:
  - apiGroups:
      - ""
    resources:      
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels: 
    app: reloader
    group: com.stakater.platform
    provider: stakater
    version: 0.0.4
    chart: "reloader-0.0.4"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader-role-binding
  namespace: tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: tools
