---
# Source: reloader/templates/role.yaml


---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    group: com.stakater.platform
    provider: stakater
    version: v0.0.39
    
  name: RELEASE-NAME-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: RELEASE-NAME-reloader
      release: "RELEASE-NAME"
  template:
    metadata:
      labels:
        app: RELEASE-NAME-reloader
        chart: "reloader-v0.0.39"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        group: com.stakater.platform
        provider: stakater
        version: v0.0.39
        
    spec:
      containers:
      - env:
        image: "stakater/reloader:v0.0.39"
        imagePullPolicy: IfNotPresent
        name: RELEASE-NAME-reloader
        args:
      serviceAccountName: reloader

---
# Source: reloader/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: RELEASE-NAME-reloader-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch

---
# Source: reloader/templates/rolebinding.yaml


---
# Source: reloader/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: RELEASE-NAME-reloader-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader
    namespace: default

---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: RELEASE-NAME-reloader
    chart: "reloader-v0.0.39"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader

